[program:ccs-web-php-fpm]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stopwaitsecs=3600